import Phaser from 'phaser';
import { VerbQuestScene } from './GameScene';
import { QUESTIONS } from './questions';
import { AudioManager, CameraController, HandTrackingController, InputController, StorageManager, type HandPoint } from './services';
import { emptyStats, heartsAfter, reachesBottomEdge, scoreHit, shuffleTargets } from './logic';
import type { GameState, InputMode, Mode, Question, RoundStats, Settings } from './types';

const $=(s:string)=>document.querySelector(s) as HTMLElement;
export class AppController {
  private game!:Phaser.Game; private scene!:VerbQuestScene; private storage=new StorageManager(); private audio=new AudioManager(); private camera=new CameraController(); private hands=new HandTrackingController(); private input?:InputController; private state:GameState='boot'; private settings:Settings; private mode:Mode='practice'; private level=1; private questions:Question[]=[]; private index=0; private stats:RoundStats=emptyStats('practice'); private startedAt=0; private feedbackTimer=0; private teamName=''; private handLost=0; private handNeedsOpen=false; private lastHandPoint?:Pick<HandPoint,'x'|'y'>; private lastPower=0; private bossActive=false; private roundTotal=0;
  constructor(){this.settings=this.storage.getSettings();this.audio.muted=this.settings.muted;this.audio.volume=this.settings.volume;void this.audio.preload();this.mount();}
  private mount(){
    document.querySelector<HTMLDivElement>('#app')!.innerHTML=`<video id="camera" autoplay muted playsinline></video><div id="cameraShade"></div><div id="game"></div><div id="handDot"></div><svg id="handSkeleton" aria-hidden="true"></svg><main id="ui">
      <section id="menu" class="panel active"><div class="brand"><span>✦</span><h1>VerbQuest</h1><small>SLINGSHOT AR</small></div><div class="mascot">🧙<i>✦</i></div><p class="tagline">ยิง Grammar Orb ให้โดนคำตอบที่ใช่!</p><button class="primary" id="play">เริ่มผจญภัย <b>➜</b></button><button class="ghost" data-open="how">วิธีเล่น</button><button class="ghost" data-open="leaderboard">กระดานทีม</button><p class="privacy">🔒 กล้องทำงานบนเครื่องของคุณเท่านั้น<br>ไม่มีโฆษณา • ไม่มีการเก็บข้อมูลส่วนตัว</p></section>
      <section id="mode" class="panel"><button class="back">‹ กลับ</button><h2>เลือกภารกิจ</h2><p>เลือกแบบที่เหมาะกับวันนี้</p><div class="modecards"><button data-mode="practice"><b>🌱 ฝึกฝน</b><span>10 ข้อ · เล็งช้า · ลองได้เรื่อย ๆ</span></button><button data-mode="challenge"><b>⚡ ท้าทาย</b><span>15 ข้อ · 3 หัวใจ · คอมโบคะแนน</span></button><button data-mode="team"><b>🏰 ทีมของเรา</b><span>10 ข้อ · บันทึกสกอร์ในเครื่อง</span></button></div></section>
      <section id="levels" class="panel"><button class="back">‹ กลับ</button><h2>เลือกด่านเวทมนตร์</h2><div class="levels"><button data-level="1">1 <span>สรรพนาม</span></button><button data-level="2">2 <span>คำนามเอกพจน์</span></button><button data-level="3">3 <span>พหูพจน์</span></button><button data-level="4">4 <span>ทบทวนผสม</span></button></div></section>
      <section id="permission" class="panel"><div class="permitIcon">📷</div><h2>เลือกกล้องสำหรับ AR</h2><p>กล้องหน้าเหมาะกับการติดตามมือและเป็นค่าเริ่มต้น ภาพไม่ออกจากอุปกรณ์ของคุณ</p><label class="cameraChoice">กล้อง <select id="cameraFacing"><option value="user">กล้องหน้า (แนะนำ)</option><option value="environment">กล้องหลัง</option></select></label><button class="primary" id="cameraStart">เปิดกล้องและเริ่ม</button><button class="ghost" id="withoutCamera">เล่นโดยไม่ใช้กล้อง</button></section>
      <section id="calibration" class="panel"><div class="permitIcon">🖐️</div><h2>ตั้งค่ามือวิเศษ</h2><p>ชูมือให้เห็น แล้วบีบนิ้วโป้งกับนิ้วชี้เพื่อจับลูกแก้ว</p><div class="calbox"><span id="calStatus">กำลังรอมือ…</span></div><button class="primary" id="calDone">พร้อมเล่น!</button><button class="ghost" id="calSkip">ใช้สัมผัส/เมาส์แทน</button></section>
      <section id="how" class="panel"><button class="back">‹ กลับ</button><h2>วิธีเล่น</h2><ol><li>อ่านประโยค แล้วหาคำ <b>am / is / are</b> ที่ถูกต้อง</li><li>จับลูกแก้วด้วยการบีบนิ้ว หรือแตะ/ลากเมาส์</li><li>ดึงกลับ เล็ง แล้วปล่อย หรือไปที่ขอบล่างเพื่อยิง</li></ol><div class="controlgrid"><span>🖐️ มือ: บีบเพื่อจับ แล้วไปที่ขอบล่างเพื่อยิง</span><span>☝️ สัมผัส: ลากแล้วปล่อย หรือชนขอบล่างเพื่อยิง</span><span>⌨️ คีย์บอร์ด: ลูกศร + Space</span></div><button class="primary back">เข้าใจแล้ว</button></section>
      <section id="leaderboard" class="panel"><button class="back">‹ กลับ</button><h2>กระดานทีมในเครื่อง</h2><div id="teams"></div></section>
      <section id="settings" class="panel"><button class="back">‹ กลับ</button><h2>ตั้งค่า</h2><label>วิธีควบคุม <select id="inputSelect"><option value="hand">ติดตามมือ</option><option value="pointer">สัมผัส / เมาส์</option><option value="keyboard">คีย์บอร์ด</option></select></label><label>เสียง <input id="volume" type="range" min="0" max="1" step=".05"></label><label><input id="motion" type="checkbox"> ลดการเคลื่อนไหว</label><label>คุณภาพ <select id="quality"><option>high</option><option>medium</option><option>low</option></select></label><button class="primary" id="saveSettings">บันทึก</button></section>
      <section id="pause" class="panel"><h2>พักก่อนก็ได้</h2><button class="primary" id="resume">เล่นต่อ</button><button class="ghost" id="openSettings">ตั้งค่า</button><button class="ghost" id="exit">กลับหน้าหลัก</button></section>
      <section id="results" class="panel results"><div class="trophy">🏆</div><h2>จบรอบแล้ว!</h2><div id="resultStats"></div><div class="recap">ทบทวน: <b>I → am</b> · <b>He, She, It → is</b> · <b>You, We, They และพหูพจน์ → are</b></div><button class="primary" id="again">เล่นอีกครั้ง</button><button class="ghost" id="mistakes">ฝึกข้อที่พลาด</button><button class="ghost" id="toMenu">หน้าหลัก</button></section>
      <section id="error" class="panel"><div class="permitIcon">✨</div><h2>เล่นต่อได้เสมอ</h2><p id="errorText"></p><button class="primary" id="errorFallback">ใช้สัมผัส / เมาส์</button><button class="ghost back">กลับหน้าหลัก</button></section>
      <section id="hud" hidden><div class="topbar"><div class="hudCard"><small id="levelName">ด่าน 1</small><strong id="progress">1 / 10</strong></div><div class="hudCard score"><small>คะแนน</small><strong id="score">0</strong></div><div class="hudControls"><button id="mute" aria-label="mute">🔊</button><button id="pauseBtn" aria-label="pause">Ⅱ</button></div></div><div class="sentence" id="sentence">I ___ a student.</div><div class="sideStats"><span id="hearts">♥♥♥</span><span id="combo">✦ x0</span><span id="coins">◉ 0</span></div><div class="inputStatus"><span id="statusDot"></span><span id="inputStatus">สัมผัส / เมาส์</span></div><div class="power"><span>พลังเวท</span><i><b id="powerFill"></b></i></div><div class="feedback" id="feedback"></div><button id="fullscreen">⛶</button></section>
      <div id="rotate">↻<br><b>หมุนหน้าจอเป็นแนวนอน</b><small>เพื่อพื้นที่เล็งที่กว้างขึ้น</small></div></main>`;
    this.bind(); this.createGame();
  }
  private createGame(){const parent=$('#game');this.game=new Phaser.Game({type:Phaser.AUTO,parent,transparent:true,backgroundColor:'rgba(0,0,0,0)',physics:{default:'matter',matter:{gravity:{x:0,y:1.35},debug:false}},scale:{mode:Phaser.Scale.RESIZE,width:innerWidth,height:innerHeight},scene:VerbQuestScene,render:{antialias:true,pixelArt:false}});this.game.events.once('ready',()=>{});this.game.events.on('hidden',()=>this.pause());setTimeout(()=>{this.scene=this.game.scene.getScene('verbquest') as VerbQuestScene;this.scene.setup({hit:a=>this.hit(a),miss:()=>this.miss(),aim:p=>this.power(p),launch:()=>this.launched()},this.settings);this.input=new InputController(parent,(p)=>{if(p.reset){this.scene.reload();return;}if(this.state==='aiming'&&this.settings.inputMode!=='hand')this.scene.pointer(p.x,p.y,p.down,p.release);});this.game.events.on('step',()=>{if(this.state==='aiming'&&this.settings.inputMode==='keyboard')this.input?.keyboard(this.scene.restPoint);});},200);}
  private bind(){
    $('#play').onclick=()=>this.show('mode');document.querySelectorAll('.back').forEach(x=>x.addEventListener('click',()=>this.show('menu')));document.querySelectorAll('[data-open]').forEach(x=>x.addEventListener('click',()=>this.show(x.getAttribute('data-open')!)));document.querySelectorAll('[data-mode]').forEach(x=>x.addEventListener('click',()=>{this.mode=x.getAttribute('data-mode') as Mode;if(this.mode==='team'){this.teamName=prompt('ชื่อทีมของคุณ')?.trim()||'Team Wizard';}this.show('levels');}));document.querySelectorAll('[data-level]').forEach(x=>x.addEventListener('click',()=>{this.level=Number(x.getAttribute('data-level'));this.show('permission');}));
    $('#cameraStart').onclick=()=>void this.startCamera();$('#withoutCamera').onclick=()=>{this.settings.inputMode='pointer';this.startRound();};$('#calDone').onclick=()=>this.startRound();$('#calSkip').onclick=()=>{this.hands.stop();this.renderHand();this.settings.inputMode='pointer';this.startRound();};$('#resume').onclick=()=>this.resume();$('#pauseBtn').onclick=()=>this.pause();$('#exit').onclick=()=>this.exit();$('#openSettings').onclick=()=>this.show('settings');$('#saveSettings').onclick=()=>this.saveSettings();$('#mute').onclick=()=>{this.settings.muted=!this.settings.muted;this.audio.muted=this.settings.muted;$('#mute').textContent=this.settings.muted?'🔇':'🔊';};$('#fullscreen').onclick=()=>void document.documentElement.requestFullscreen?.();$('#again').onclick=()=>this.startRound();$('#mistakes').onclick=()=>this.startMistakes();$('#toMenu').onclick=()=>this.exit();$('#errorFallback').onclick=()=>{this.settings.inputMode='pointer';this.startRound();};
    document.addEventListener('visibilitychange',()=>{if(document.hidden)this.pause();});document.addEventListener('click',e=>{if((e.target as Element).closest('button'))this.audio.play('click');});
  }
  private show(id:string){document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));$(`#${id}`).classList.add('active');if(id==='leaderboard')this.renderTeams();if(id==='permission')(document.querySelector('#cameraFacing') as HTMLSelectElement).value=this.settings.cameraFacing;if(id==='settings'){(document.querySelector('#inputSelect') as HTMLSelectElement).value=this.settings.inputMode;(document.querySelector('#volume') as HTMLInputElement).value=String(this.settings.volume);(document.querySelector('#motion') as HTMLInputElement).checked=this.settings.reducedMotion;(document.querySelector('#quality') as HTMLSelectElement).value=this.settings.quality;}}
  private async startCamera(){this.audio.unlock();this.settings.cameraFacing=(document.querySelector('#cameraFacing') as HTMLSelectElement).value as Settings['cameraFacing'];this.settings.inputMode='hand';this.storage.saveSettings(this.settings);try{await this.camera.start($('#camera') as HTMLVideoElement,this.settings.cameraFacing);this.show('calibration');void this.startHands();}catch(e){this.fail(e instanceof Error?e.message:'เปิดกล้องไม่ได้');}}
  private async startHands(){const status=$('#calStatus');status.textContent='กำลังโหลดระบบติดตามมือ…';try{await this.hands.start($('#camera') as HTMLVideoElement,p=>this.handleHand(p),this.settings.cameraFacing==='user',message=>this.handTrackingFailed(message));status.textContent='กำลังรอมือ…';}catch(e){this.handTrackingFailed(e instanceof Error?e.message:'โหลดการติดตามมือไม่สำเร็จ');}}
  private handTrackingFailed(message:string){this.hands.stop();this.settings.inputMode='pointer';this.storage.saveSettings(this.settings);if(this.input)this.input.mode='pointer';$('#handDot').hidden=true;this.renderHand();if(this.state==='aiming'||this.state==='projectileFlight'){$('#inputStatus').textContent='ติดตามมือหยุดทำงาน — ใช้สัมผัส / เมาส์';return;}this.fail(`${message} เล่นด้วยสัมผัสหรือเมาส์ได้ทันที`);}
  private handleHand(p?:HandPoint){const status=$('#calStatus');this.renderHand(p);if(p){const dot=$('#handDot');dot.style.transform=`translate(${p.x-14}px,${p.y-14}px)`;dot.classList.toggle('pinch',p.pinch);dot.hidden=false;this.handLost=0;if(!p.pinch){this.handNeedsOpen=false;this.lastHandPoint=undefined;status.textContent='พบมือแล้ว! บีบนิ้วแล้วลองเล็ง';if(this.state==='aiming')this.scene.pointer(p.x,p.y,false,true,true);return;}if(this.handNeedsOpen){status.textContent='กางนิ้วก่อน แล้วบีบเพื่อยิงครั้งต่อไป';return;}status.textContent='จับลูกแก้วแล้ว — ดึงเพื่อเล็ง';this.lastHandPoint={x:p.x,y:p.y};if(this.state==='aiming'){this.scene.pointer(p.x,p.y,true,false,true);if(reachesBottomEdge(p.y,innerHeight,24)){this.lastHandPoint=undefined;this.handNeedsOpen=true;this.scene.pointer(p.x,p.y,false,true,true);}}return;}$('#handDot').hidden=true;if(!this.handLost)this.handLost=performance.now();if(this.state==='aiming'&&this.lastHandPoint&&performance.now()-this.handLost>150){const point=this.lastHandPoint;this.lastHandPoint=undefined;this.handNeedsOpen=true;this.scene.pointer(point.x,point.y,false,true,true);}if(performance.now()-this.handLost>600&&this.state==='aiming'){$('#inputStatus').textContent='กำลังหามือ… ใช้สัมผัสได้';this.scene.hideCursor();}}
  private renderHand(point?:HandPoint){const svg=$('#handSkeleton') as unknown as SVGSVGElement;if(!point){svg.innerHTML='';svg.style.display='none';return;}const links=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[17,18],[18,19],[19,20],[0,17]];svg.style.display='block';svg.setAttribute('viewBox',`0 0 ${innerWidth} ${innerHeight}`);svg.innerHTML=`<g class="hand-bones">${links.map(([a,b])=>`<line x1="${point.joints[a].x}" y1="${point.joints[a].y}" x2="${point.joints[b].x}" y2="${point.joints[b].y}"/>`).join('')}</g><g class="hand-joints">${point.joints.map((j,i)=>`<circle cx="${j.x}" cy="${j.y}" r="${i===8||i===4?6:4}"/>`).join('')}</g>`;}
  private startRound(list?:Question[]){this.showGame();this.audio.unlock();this.state='aiming';this.stats=emptyStats(this.mode);const source=list||QUESTIONS.filter(q=>q.difficulty===this.level);const count=this.mode==='challenge'?15:10;this.questions=shuffleTargets(source.length>=count?source:QUESTIONS).slice(0,count);this.roundTotal=this.questions.length;this.bossActive=false;this.index=0;this.next();}
  private showGame(){document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));$('#hud').hidden=false;this.game.loop.wake();this.input!.mode=this.settings.inputMode;this.audio.muted=this.settings.muted;this.audio.volume=this.settings.volume;}
  private next(){if(this.index>=this.questions.length){if(!this.bossActive){this.startBoss();return;}this.finish();return;}this.state='aiming';this.lastPower=0;const q=this.questions[this.index];this.startedAt=performance.now();this.scene.settings=this.settings;this.scene.question(q);$('#sentence').textContent=q.sentence;$('#progress').textContent=this.bossActive?`🛡️ ${this.index+1} / 3`:`${this.index+1} / ${this.questions.length}`;$('#levelName').textContent=this.bossActive?'🐉 Grammar Dragon · Shield':`ด่าน ${this.level} · ${q.category}`;$('#inputStatus').textContent=this.settings.inputMode==='hand'?'🖐️ ติดตามมือ':this.settings.inputMode==='keyboard'?'⌨️ คีย์บอร์ด':'☝️ สัมผัส / เมาส์';$('#feedback').textContent='';this.hud();}
  private startBoss(){this.bossActive=true;this.questions=shuffleTargets(QUESTIONS.filter(q=>q.difficulty===this.level)).slice(0,3);this.index=0;this.state='boss';this.feedback('🐉 Grammar Dragon มาแล้ว!<small>ยิงคำตอบที่ถูกเพื่อทำลายโล่ 3 ชั้น</small>','good');setTimeout(()=>this.next(),950);}
  private hit(answer:'am'|'is'|'are'){if(this.state!=='projectileFlight'&&this.state!=='aiming')return;this.state='hitFeedback';const q=this.questions[this.index],correct=q.answer===answer,elapsed=performance.now()-this.startedAt;this.stats.attempted++;if(correct){this.stats.correct++;this.stats.combo++;this.stats.highestCombo=Math.max(this.stats.combo,this.stats.highestCombo);const points=scoreHit(true,elapsed,this.stats.combo,elapsed<1800,this.stats.combo>=10);this.stats.score+=points;this.stats.answerTimes.push(elapsed);if(elapsed<1800)this.stats.directHits++;if(this.stats.combo===2){this.stats.coins+=3;setTimeout(()=>this.audio.play('coin'),220);}if(this.stats.combo===7)this.stats.shield=true;if(navigator.vibrate)navigator.vibrate(25);this.audio.play('correct');this.feedback(`✓ Correct! / ถูกต้อง!<small>${q.sentence.replace('___',q.answer)}<br>${q.explanation} +${points}</small>`,'good');}else{this.stats.combo=0;this.stats.mistakes[q.category]=(this.stats.mistakes[q.category]||0)+1;const h=heartsAfter(this.mode,this.stats.hearts,false,this.stats.shield);this.stats.hearts=h.hearts;this.stats.shield=h.shield;this.audio.play('wrong');this.feedback(`✕ ลองใหม่ในข้อต่อไป<small>${q.sentence.replace('___',q.answer)}<br>${q.explanation}</small>`,'bad');}this.scene.feedback(answer,correct);this.hud();setTimeout(()=>{this.index++;this.next();},correct?1300:1800);}
  private miss(){if(this.state!=='projectileFlight')return;this.audio.play('miss');const q=this.questions[this.index];if(this.mode==='practice'){this.feedback('ลองเล็งอีกครั้งได้เลย ✦','bad');setTimeout(()=>this.next(),750);return;}this.state='hitFeedback';this.stats.combo=0;this.stats.attempted++;this.stats.mistakes[q.category]=(this.stats.mistakes[q.category]||0)+1;const h=heartsAfter(this.mode,this.stats.hearts,false,this.stats.shield);this.stats.hearts=h.hearts;this.stats.shield=h.shield;this.hud();this.feedback('ลูกแก้วหลุดไปแล้ว ลองข้อต่อไป!','bad');setTimeout(()=>{if(this.stats.hearts<=0)this.finish();else{this.index++;this.next();}},1000);}
  private power(p:number){$('#powerFill').style.width=`${p*100}%`;if(p>.03&&this.lastPower<=.03)this.audio.play('grab');this.lastPower=p;}
  private launched(){this.state='projectileFlight';this.lastPower=0;this.audio.play('launch');}
  private feedback(html:string,kind:string){const x=$('#feedback');x.innerHTML=html;x.className=`feedback show ${kind}`;clearTimeout(this.feedbackTimer);this.feedbackTimer=window.setTimeout(()=>x.className='feedback',1500);}
  private hud(){$('#score').textContent=String(this.stats.score);$('#hearts').textContent=this.mode==='challenge'?'♥'.repeat(this.stats.hearts)+(this.stats.shield?' 🛡️':''):'∞';$('#combo').textContent=`✦ x${this.stats.combo}${this.stats.combo>=10?' FEVER!':''}`;$('#coins').textContent=`◉ ${this.stats.coins}`;}
  private pause(){if(this.state==='aiming'||this.state==='projectileFlight'){this.state='paused';this.game.loop.sleep();this.show('pause');}}
  private resume(){this.state='aiming';this.showGame();}
  private saveSettings(){this.settings.inputMode=(document.querySelector('#inputSelect') as HTMLSelectElement).value as InputMode;this.settings.volume=Number((document.querySelector('#volume') as HTMLInputElement).value);this.settings.reducedMotion=(document.querySelector('#motion') as HTMLInputElement).checked;this.settings.quality=(document.querySelector('#quality') as HTMLSelectElement).value as Settings['quality'];this.storage.saveSettings(this.settings);this.input!.mode=this.settings.inputMode;this.show('pause');}
  private finish(){this.state='results';$('#hud').hidden=true;this.game.loop.sleep();if(this.mode==='team')this.storage.addTeam(this.teamName,this.stats.score);const accuracy=this.stats.attempted?Math.round(this.stats.correct/this.stats.attempted*100):0;const average=this.stats.answerTimes.length?Math.round(this.stats.answerTimes.reduce((a,b)=>a+b,0)/this.stats.answerTimes.length/100)/10:0;$('#resultStats').innerHTML=`<div><b>${this.stats.score}</b><small>คะแนน</small></div><div><b>${this.stats.correct}/${this.roundTotal}</b><small>ถูกต้อง</small></div><div><b>${accuracy}%</b><small>ความแม่นยำ</small></div><div><b>x${this.stats.highestCombo}</b><small>คอมโบสูงสุด</small></div><div><b>${average}s</b><small>เวลาเฉลี่ย</small></div><div><b>${this.stats.coins}</b><small>เหรียญ</small></div><p>${Object.keys(this.stats.mistakes).length?'ทบทวนเพิ่ม: '+Object.keys(this.stats.mistakes).join(', '):'ยอดเยี่ยม! คุณตอบได้ครบทุกหมวด'}</p>`;this.audio.play('victory');this.show('results');}
  private startMistakes(){const cats=Object.keys(this.stats.mistakes);const list=cats.length?QUESTIONS.filter(q=>cats.includes(q.category)):QUESTIONS.slice(0,10);this.mode='practice';this.startRound(list);}
  private renderTeams(){const rows=this.storage.teams();$('#teams').innerHTML=rows.length?rows.map((r,i)=>`<p><b>${i+1}. ${r.name}</b><span>${r.score} ✦ <small>${r.date}</small></span></p>`).join(''):'<p>ยังไม่มีทีม ลองเล่น Team Mode!</p>';}
  private fail(msg:string){this.state='error';$('#errorText').textContent=msg;this.show('error');}
  private exit(){this.camera.stop();this.hands.stop();this.handNeedsOpen=false;this.lastHandPoint=undefined;($('#camera') as HTMLVideoElement).srcObject=null;$('#handDot').hidden=true;this.renderHand();$('#hud').hidden=true;this.game.loop.wake();this.show('menu');this.state='menu';}
}
