import type { Question } from './types';
const make = (category:string, difficulty:number, rows:[string,string,'am'|'is'|'are',string][], start:number):Question[] => rows.map(([sentence, subject, answer, explanation], i) => ({ id:`${category}-${String(start+i).padStart(3,'0')}`, sentence, subject, answer, explanation, category, difficulty }));
export const QUESTIONS: Question[] = [
...make('pronoun',1,[
['I ___ a student.','I','am','Use “am” with I.'],['I ___ happy today.','I','am','Use “am” with I.'],['I ___ from Thailand.','I','am','Use “am” with I.'],['I ___ ready to play.','I','am','Use “am” with I.'],
['He ___ tall.','He','is','Use “is” with he.'],['He ___ my brother.','He','is','Use “is” with he.'],['She ___ happy.','She','is','Use “is” with she.'],['She ___ a singer.','She','is','Use “is” with she.'],['It ___ a small dog.','It','is','Use “is” with it.'],['It ___ blue.','It','is','Use “is” with it.'],
['You ___ my friend.','You','are','Use “are” with you.'],['You ___ very kind.','You','are','Use “are” with you.'],['We ___ ready.','We','are','Use “are” with we.'],['We ___ in class.','We','are','Use “are” with we.'],['They ___ at school.','They','are','Use “are” with they.'],['They ___ my friends.','They','are','Use “are” with they.'],
],1),
...make('singular',2,[
['Tom ___ ten years old.','Tom','is','Use “is” with one person.'],['My mother ___ a teacher.','My mother','is','Use “is” with one person.'],['The cat ___ under the table.','The cat','is','Use “is” with one thing.'],['This book ___ new.','This book','is','Use “is” with one thing.'],['Anna ___ from Thailand.','Anna','is','Use “is” with one person.'],['The sun ___ hot.','The sun','is','Use “is” with one thing.'],['My dad ___ funny.','My dad','is','Use “is” with one person.'],['The baby ___ asleep.','The baby','is','Use “is” with one person.'],['A bird ___ in the tree.','A bird','is','Use “is” with one animal.'],['The cake ___ sweet.','The cake','is','Use “is” with one thing.'],['My pencil ___ yellow.','My pencil','is','Use “is” with one thing.'],['The room ___ clean.','The room','is','Use “is” with one place.'],['A frog ___ green.','A frog','is','Use “is” with one animal.'],['The teacher ___ nice.','The teacher','is','Use “is” with one person.'],['That bag ___ heavy.','That bag','is','Use “is” with one thing.'],['My school ___ big.','My school','is','Use “is” with one place.'],
],1),
...make('plural',3,[
['The dogs ___ hungry.','The dogs','are','Use “are” with plural nouns.'],['My friends ___ happy.','My friends','are','Use “are” with plural nouns.'],['Tom and Jane ___ classmates.','Tom and Jane','are','Use “are” with two people.'],['The books ___ on the table.','The books','are','Use “are” with plural nouns.'],['These pencils ___ red.','These pencils','are','Use “are” with plural nouns.'],['My shoes ___ wet.','My shoes','are','Use “are” with plural nouns.'],['The children ___ in the park.','The children','are','Use “are” with plural nouns.'],['Cats and dogs ___ animals.','Cats and dogs','are','Use “are” with two groups.'],['Those flowers ___ pretty.','Those flowers','are','Use “are” with plural nouns.'],['The apples ___ fresh.','The apples','are','Use “are” with plural nouns.'],['My parents ___ busy.','My parents','are','Use “are” with plural nouns.'],['The stars ___ bright.','The stars','are','Use “are” with plural nouns.'],['Ben and I ___ teammates.','Ben and I','are','Use “are” with two people.'],['The toys ___ in the box.','The toys','are','Use “are” with plural nouns.'],['Our hands ___ clean.','Our hands','are','Use “are” with plural nouns.'],['The buses ___ yellow.','The buses','are','Use “are” with plural nouns.'],
],1),
...make('mixed',4,[
['I ___ excited for art class.','I','am','Use “am” with I.'],['My rabbit ___ soft.','My rabbit','is','Use “is” with one animal.'],['We ___ a good team.','We','are','Use “are” with we.'],['The twins ___ smiling.','The twins','are','Use “are” with plural nouns.'],['She ___ my best friend.','She','is','Use “is” with she.'],['You ___ welcome here.','You','are','Use “are” with you.'],['The robot ___ helpful.','The robot','is','Use “is” with one thing.'],['They ___ ready for lunch.','They','are','Use “are” with they.'],['I ___ good at drawing.','I','am','Use “am” with I.'],['The rainbows ___ colorful.','The rainbows','are','Use “are” with plural nouns.'],['He ___ in the library.','He','is','Use “is” with he.'],['My cousins ___ funny.','My cousins','are','Use “are” with plural nouns.'],
],1)
];
